site_name: Deceptgold Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs
    - search.suggest
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
  - markdown-exec
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
nav:
  - Home: index.md
  - CLI Reference: Commands.md
  - Installation: Installation.md
  - about: About.md
extra:
  generator: false