import subprocess
from datetime import datetime


def main():
    # git-cliff will use the config file located in the utils directory
    result = subprocess.run(
        "git-cliff --unreleased --config utils/config/cliff.toml",
        shell=True,
        check=True,
        capture_output=True,
        text=True,
    )
    output = result.stdout or ""
    if "## " not in output:
        try:
            version = (
                subprocess.run(
                    "poetry version -s",
                    shell=True,
                    check=True,
                    capture_output=True,
                    text=True,
                )
                .stdout.strip()
            )
        except Exception:
            version = "In This Version"

        date = datetime.utcnow().strftime("%Y-%m-%d")
        output = (
            "# Changelog\n"
            "All notable changes to this project will be documented in this file.\n\n"
            f"## [{version}] - {date}\n"
            "### 💼 Other\n"
            "- Initial release\n\n"
            "<!-- generated by git-cliff -->\n"
        )
    with open("src/deceptgold/CHANGELOG", "w") as f:
        f.write(output)

if __name__ == "__main__":
    main()